package ReferenceLanguage.actions;

/*Generated by MPS */

import jetbrains.mps.actions.descriptor.BaseActionAspectDescriptor;
import jetbrains.mps.openapi.actions.descriptor.ActionAspectDescriptor;
import java.util.Collection;
import jetbrains.mps.openapi.actions.descriptor.NodeFactory;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;

public class ActionAspectDescriptorImpl extends BaseActionAspectDescriptor implements ActionAspectDescriptor {
  private static final String LANGUAGE_FQ_NAME = "ReferenceLanguage";

  @Override
  public Collection<NodeFactory> getFactories(SAbstractConcept concept) {
    if (LANGUAGE_FQ_NAME.equals(concept.getLanguage().getQualifiedName())) {
      switch (concept.getName()) {
        case "Article":
          return Collections.<NodeFactory>singletonList(new ArticleNum.NodeFactory_1250284339136412930());
        case "InBook":
          return Collections.<NodeFactory>singletonList(new InBookNumber.NodeFactory_1250284339137095562());
        case "InProceedings":
          return Collections.<NodeFactory>singletonList(new InProceedingsNum.NodeFactory_1250284339137110870());
        case "PhdThesis":
          return Collections.<NodeFactory>singletonList(new PhdThesisNum.NodeFactory_1250284339136916490());
        default:
      }
    }
    return Collections.<NodeFactory>emptyList();
  }

}
