package ReferenceLanguage.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.Sequence;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class Incollection_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("[");
    tgs.append(SPropertyOperations.getInteger(ctx.getPrimaryInput(), PROPS.serNumber$3owZ) + "] ");
    {
      Iterable<SNode> collection = SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.authors$svUa);
      final SNode lastItem = Sequence.fromIterable(collection).last();
      for (SNode item : collection) {
        tgs.appendNode(item);
        if (item != lastItem) {
          tgs.append(", ");
        }
      }
    }
    tgs.append(". ");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.title$swQe));
    tgs.append(". ");
    if (SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.editor$veGN) != null) {
      tgs.append(" In " + SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.editor$veGN) + ", editors, ");
    }
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.booktitle$sxkg));
    if (SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.pages$v88n) != null) {
      tgs.append(", pages " + SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.pages$v88n) + ". ");
    }
    if (SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.publisher$v0BR) != null) {
      tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.publisher$v0BR) + ", ");
    }
    if (SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.address$v6Ih) != null) {
      tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.address$v6Ih) + ", ");
    }
    tgs.append(SPropertyOperations.getInteger(ctx.getPrimaryInput(), PROPS.year$uZFN) + ".");
  }

  private static final class PROPS {
    /*package*/ static final SProperty serNumber$3owZ = MetaAdapterFactory.getProperty(0x28685c99a6841f2L, 0x9f1069a76b1b1f42L, 0x1e3ba47b555fd52cL, 0x1159e6fb6e9e4ecbL, "serNumber");
    /*package*/ static final SProperty title$swQe = MetaAdapterFactory.getProperty(0x28685c99a6841f2L, 0x9f1069a76b1b1f42L, 0x536290f98ef22695L, 0x536290f98ef226a0L, "title");
    /*package*/ static final SProperty editor$veGN = MetaAdapterFactory.getProperty(0x28685c99a6841f2L, 0x9f1069a76b1b1f42L, 0x536290f98ef22695L, 0x536290f98ef226bbL, "editor");
    /*package*/ static final SProperty booktitle$sxkg = MetaAdapterFactory.getProperty(0x28685c99a6841f2L, 0x9f1069a76b1b1f42L, 0x536290f98ef22695L, 0x536290f98ef226a2L, "booktitle");
    /*package*/ static final SProperty pages$v88n = MetaAdapterFactory.getProperty(0x28685c99a6841f2L, 0x9f1069a76b1b1f42L, 0x536290f98ef22695L, 0x536290f98ef226b4L, "pages");
    /*package*/ static final SProperty publisher$v0BR = MetaAdapterFactory.getProperty(0x28685c99a6841f2L, 0x9f1069a76b1b1f42L, 0x536290f98ef22695L, 0x536290f98ef226a9L, "publisher");
    /*package*/ static final SProperty address$v6Ih = MetaAdapterFactory.getProperty(0x28685c99a6841f2L, 0x9f1069a76b1b1f42L, 0x536290f98ef22695L, 0x536290f98ef226aeL, "address");
    /*package*/ static final SProperty year$uZFN = MetaAdapterFactory.getProperty(0x28685c99a6841f2L, 0x9f1069a76b1b1f42L, 0x536290f98ef22695L, 0x536290f98ef226a5L, "year");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink authors$svUa = MetaAdapterFactory.getContainmentLink(0x28685c99a6841f2L, 0x9f1069a76b1b1f42L, 0x536290f98ef22695L, 0x536290f98ef2269cL, "authors");
  }
}
