package ReferenceLanguage.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class MasterThesis_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.author$lVA4), PROPS.firstName$_Jim) + " ");
    if (SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.author$lVA4), PROPS.middleName$_JZp) != null) {
      tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.author$lVA4), PROPS.middleName$_JZp) + " ");
    }
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.author$lVA4), PROPS.surname$_Q5N) + ". ");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.title$lW46) + ", ");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.school$lWy8) + ", ");
    if (SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.address$m36$) != null) {
      tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.address$m36$) + ", ");
    }
    if (SPropertyOperations.getEnum(ctx.getPrimaryInput(), PROPS.month$m4hD) != null) {
      tgs.append(SPropertyOperations.getEnum(ctx.getPrimaryInput(), PROPS.month$m4hD) + ". ");
    }
    tgs.append(SPropertyOperations.getInteger(ctx.getPrimaryInput(), PROPS.year$lXfb) + ".");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink author$lVA4 = MetaAdapterFactory.getContainmentLink(0x28685c99a6841f2L, 0x9f1069a76b1b1f42L, 0x1da23d5c1241dc25L, 0x1da23d5c1241dc26L, "author");
  }

  private static final class PROPS {
    /*package*/ static final SProperty firstName$_Jim = MetaAdapterFactory.getProperty(0x28685c99a6841f2L, 0x9f1069a76b1b1f42L, 0x1a03dc0acd1eab40L, 0x1a03dc0acd30fd73L, "firstName");
    /*package*/ static final SProperty middleName$_JZp = MetaAdapterFactory.getProperty(0x28685c99a6841f2L, 0x9f1069a76b1b1f42L, 0x1a03dc0acd1eab40L, 0x1a03dc0acd30fd76L, "middleName");
    /*package*/ static final SProperty surname$_Q5N = MetaAdapterFactory.getProperty(0x28685c99a6841f2L, 0x9f1069a76b1b1f42L, 0x1a03dc0acd1eab40L, 0x1a03dc0acd30fd7bL, "surname");
    /*package*/ static final SProperty title$lW46 = MetaAdapterFactory.getProperty(0x28685c99a6841f2L, 0x9f1069a76b1b1f42L, 0x1da23d5c1241dc25L, 0x1da23d5c1241dc28L, "title");
    /*package*/ static final SProperty school$lWy8 = MetaAdapterFactory.getProperty(0x28685c99a6841f2L, 0x9f1069a76b1b1f42L, 0x1da23d5c1241dc25L, 0x1da23d5c1241dc2aL, "school");
    /*package*/ static final SProperty address$m36$ = MetaAdapterFactory.getProperty(0x28685c99a6841f2L, 0x9f1069a76b1b1f42L, 0x1da23d5c1241dc25L, 0x1da23d5c1241dc31L, "address");
    /*package*/ static final SProperty month$m4hD = MetaAdapterFactory.getProperty(0x28685c99a6841f2L, 0x9f1069a76b1b1f42L, 0x1da23d5c1241dc25L, 0x1da23d5c1241dc36L, "month");
    /*package*/ static final SProperty year$lXfb = MetaAdapterFactory.getProperty(0x28685c99a6841f2L, 0x9f1069a76b1b1f42L, 0x1da23d5c1241dc25L, 0x1da23d5c1241dc2dL, "year");
  }
}
