package ReferenceLanguage.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Proceedings_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("[");
    tgs.append(SPropertyOperations.getInteger(ctx.getPrimaryInput(), PROPS.serNumber$laA) + "] ");
    if (SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.editor$vU89) != null) {
      tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.editor$vU89) + ", editors. ");
    }
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.title$v_0J));
    if (SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.volume$vF79) != null) {
      tgs.append(", volume " + SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.volume$vF79));
    }
    if (SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.series$vEq6) != null) {
      tgs.append(" of " + SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.series$vEq6));
    }
    if (SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.address$vM9B) != null) {
      tgs.append(", " + SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.address$vM9B));
    }
    tgs.append(", " + SPropertyOperations.getInteger(ctx.getPrimaryInput(), PROPS.year$vNzH) + ".");
  }

  private static final class PROPS {
    /*package*/ static final SProperty serNumber$laA = MetaAdapterFactory.getProperty(0x28685c99a6841f2L, 0x9f1069a76b1b1f42L, 0x536290f98ef226d4L, 0x21c2335636e83186L, "serNumber");
    /*package*/ static final SProperty editor$vU89 = MetaAdapterFactory.getProperty(0x28685c99a6841f2L, 0x9f1069a76b1b1f42L, 0x536290f98ef226d4L, 0x536290f98ef226f0L, "editor");
    /*package*/ static final SProperty title$v_0J = MetaAdapterFactory.getProperty(0x28685c99a6841f2L, 0x9f1069a76b1b1f42L, 0x536290f98ef226d4L, 0x536290f98ef226d5L, "title");
    /*package*/ static final SProperty volume$vF79 = MetaAdapterFactory.getProperty(0x28685c99a6841f2L, 0x9f1069a76b1b1f42L, 0x536290f98ef226d4L, 0x536290f98ef226daL, "volume");
    /*package*/ static final SProperty series$vEq6 = MetaAdapterFactory.getProperty(0x28685c99a6841f2L, 0x9f1069a76b1b1f42L, 0x536290f98ef226d4L, 0x536290f98ef226d7L, "series");
    /*package*/ static final SProperty address$vM9B = MetaAdapterFactory.getProperty(0x28685c99a6841f2L, 0x9f1069a76b1b1f42L, 0x536290f98ef226d4L, 0x536290f98ef226e3L, "address");
    /*package*/ static final SProperty year$vNzH = MetaAdapterFactory.getProperty(0x28685c99a6841f2L, 0x9f1069a76b1b1f42L, 0x536290f98ef226d4L, 0x536290f98ef226e9L, "year");
  }
}
