package ReferenceLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_Month extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Month() {
    super(0x28685c99a6841f2L, 0x9f1069a76b1b1f42L, 0x1a03dc0acd30fcccL, "Month", "r:7832ba79-122e-452d-b064-5ac586f5bd58(ReferenceLanguage.structure)/1874583808866581708");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_JAN_0 = new EnumerationDescriptor.MemberDescriptor("JAN", "JAN", 0x1a03dc0acd30fccdL, "r:7832ba79-122e-452d-b064-5ac586f5bd58(ReferenceLanguage.structure)/1874583808866581709");
  private final EnumerationDescriptor.MemberDescriptor myMember_FEB_0 = new EnumerationDescriptor.MemberDescriptor("FEB", "FEB", 0x1a03dc0acd30fcceL, "r:7832ba79-122e-452d-b064-5ac586f5bd58(ReferenceLanguage.structure)/1874583808866581710");
  private final EnumerationDescriptor.MemberDescriptor myMember_MAR_0 = new EnumerationDescriptor.MemberDescriptor("MAR", "MAR", 0x1a03dc0acd30fcd3L, "r:7832ba79-122e-452d-b064-5ac586f5bd58(ReferenceLanguage.structure)/1874583808866581715");
  private final EnumerationDescriptor.MemberDescriptor myMember_APR_0 = new EnumerationDescriptor.MemberDescriptor("APR", "APR", 0x1a03dc0acd30fcdaL, "r:7832ba79-122e-452d-b064-5ac586f5bd58(ReferenceLanguage.structure)/1874583808866581722");
  private final EnumerationDescriptor.MemberDescriptor myMember_MAY_0 = new EnumerationDescriptor.MemberDescriptor("MAY", "MAY", 0x1a03dc0acd30fce3L, "r:7832ba79-122e-452d-b064-5ac586f5bd58(ReferenceLanguage.structure)/1874583808866581731");
  private final EnumerationDescriptor.MemberDescriptor myMember_JUN_0 = new EnumerationDescriptor.MemberDescriptor("JUN", "JUN", 0x1a03dc0acd30fceeL, "r:7832ba79-122e-452d-b064-5ac586f5bd58(ReferenceLanguage.structure)/1874583808866581742");
  private final EnumerationDescriptor.MemberDescriptor myMember_JUL_0 = new EnumerationDescriptor.MemberDescriptor("JUL", "JUL", 0x1a03dc0acd30fcfbL, "r:7832ba79-122e-452d-b064-5ac586f5bd58(ReferenceLanguage.structure)/1874583808866581755");
  private final EnumerationDescriptor.MemberDescriptor myMember_AUG_0 = new EnumerationDescriptor.MemberDescriptor("AUG", "AUG", 0x1a03dc0acd30fd0aL, "r:7832ba79-122e-452d-b064-5ac586f5bd58(ReferenceLanguage.structure)/1874583808866581770");
  private final EnumerationDescriptor.MemberDescriptor myMember_SEP_0 = new EnumerationDescriptor.MemberDescriptor("SEP", "SEP", 0x1a03dc0acd30fd1bL, "r:7832ba79-122e-452d-b064-5ac586f5bd58(ReferenceLanguage.structure)/1874583808866581787");
  private final EnumerationDescriptor.MemberDescriptor myMember_OCT_0 = new EnumerationDescriptor.MemberDescriptor("OCT", "OCT", 0x1a03dc0acd30fd2eL, "r:7832ba79-122e-452d-b064-5ac586f5bd58(ReferenceLanguage.structure)/1874583808866581806");
  private final EnumerationDescriptor.MemberDescriptor myMember_NOV_0 = new EnumerationDescriptor.MemberDescriptor("NOV", "NOV", 0x1a03dc0acd30fd43L, "r:7832ba79-122e-452d-b064-5ac586f5bd58(ReferenceLanguage.structure)/1874583808866581827");
  private final EnumerationDescriptor.MemberDescriptor myMember_DEC_0 = new EnumerationDescriptor.MemberDescriptor("DEC", "DEC", 0x1a03dc0acd30fd5aL, "r:7832ba79-122e-452d-b064-5ac586f5bd58(ReferenceLanguage.structure)/1874583808866581850");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x28685c99a6841f2L, 0x9f1069a76b1b1f42L, 0x1a03dc0acd30fcccL, 0x1a03dc0acd30fccdL, 0x1a03dc0acd30fcceL, 0x1a03dc0acd30fcd3L, 0x1a03dc0acd30fcdaL, 0x1a03dc0acd30fce3L, 0x1a03dc0acd30fceeL, 0x1a03dc0acd30fcfbL, 0x1a03dc0acd30fd0aL, 0x1a03dc0acd30fd1bL, 0x1a03dc0acd30fd2eL, 0x1a03dc0acd30fd43L, 0x1a03dc0acd30fd5aL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_JAN_0, myMember_FEB_0, myMember_MAR_0, myMember_APR_0, myMember_MAY_0, myMember_JUN_0, myMember_JUL_0, myMember_AUG_0, myMember_SEP_0, myMember_OCT_0, myMember_NOV_0, myMember_DEC_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_JAN_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "JAN":
        return myMember_JAN_0;
      case "FEB":
        return myMember_FEB_0;
      case "MAR":
        return myMember_MAR_0;
      case "APR":
        return myMember_APR_0;
      case "MAY":
        return myMember_MAY_0;
      case "JUN":
        return myMember_JUN_0;
      case "JUL":
        return myMember_JUL_0;
      case "AUG":
        return myMember_AUG_0;
      case "SEP":
        return myMember_SEP_0;
      case "OCT":
        return myMember_OCT_0;
      case "NOV":
        return myMember_NOV_0;
      case "DEC":
        return myMember_DEC_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
